name = "doh-csv-worker"
main = "src/worker.js"
compatibility_date = "2026-09-30"

[vars]
CONFIG_URL = "https://raw.githubusercontent.com/cnbilinyj/doh-csv-worker/main/dns.csv"
CONFIG_CACHE_TTL_SECONDS = "60"
ENABLE_WEBUI = "true"
